### ISSUE TITLE
Range Generation method can produce impossible range pairs

### ISSUE THREAD

**Issue by bobbiesbob** [lifrordi/DeepStack-Leduc#16]
Since the range generation is done for each player independently, there can be impossible range pairs produced such as:

P1:
- A: 70%
- K: 10%
- Q: 20%

P2:
- A: 50%
- K: 25%
- Q: 25%

It's not possible for P1 to have A 70% of the time and P2 also having A 50% of the time.

The impossible ranges could skew the models produced

**Comment by lifrordi** [comment]
This is not what ranges exactly mean in this setting. 
Given these 'ranges' you can easily compute the probability of all the possible pairs (P1:A, P2:A), (P1:A, P2:B), etc.
So in a sense these ranges just encode probabilities of all the possible pairs.
Now the pair probabilities might not sum to 1 due to blocking effect, which is fine.

What you mean by "impossible" ranges in an extreme case means that all of the pairs have zero probability, which is fine.

**Comment by bobbiesbob** [comment]
Thanks for clarification
