### ISSUE TITLE
Texas Hold'em

### ISSUE THREAD

**Issue by meysamgolm** [lifrordi/DeepStack-Leduc#3]
Hi,

Thank you for such an interesting research topic. Currently I am developing an alternative structure of deep stack using LSTM networks. I'd like to compare my results against both of Leduc and Texas Hold'em. I wonder if we can have access to dataset and trained model of deepstack for Texas Hold'em.

Thanks

**Comment by filostrato** [comment]
I'm also highly interested in an implementation for Texas hold'em, both to compare with my own implementations and to train against as a player. Would it be a lot of work to modify the Leduc code to change it into Texas? I see one of the parameters in `game_settings` is `board_card_count`, but seems nontrivial to me how to change that into the public card structure of Texas (3 card flop, then one more card twice, etc.).

**Comment by lifrordi** [comment]
Hi,
thanks for the interest.

We get questions about Texas Hold'em a lot. Since the original DeepStack study published in Science happened in this particular game format, it's understandable.

Unfortunately, the very reason we spent time re-implementing the DeepStack algorithm for Leduc is that we did not wanted to release the implementation for such game. Otherwise, anyone could simply download a program that beats professional poker players in a game  that is commonly played online for non trivial money. The point of this repository is to make the algorithm publicly available and present the science on a game that shows how the algorithm works, is simple enough to measure the quality of the solution and is not played by human players. Thus this particular code does not run Texas Hold'em not is intended to be easy to do so via few adjustments.
